### ISSUE TITLE
Release Notification

### ISSUE THREAD

**Issue by AndreyFilchenkov** [ReleaseDaemonTestOrganization/Notifications#1]
This issue is reserved for ReleaseDaemon release draft notifications.

**Comment by SC-AFI** [comment]
@SC-AFI release draft was created [Sitecore.Support.ReleaseDaemon.GitHub.GitHubRepositoryInfo@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
@SC-AFI release draft was created [Sitecore.Support.ReleaseDaemon.GitHub.GitHubRepositoryInfo@8.1.1.2](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
@SC-AFI release draft was created [Sitecore.Support.ReleaseDaemon.GitHub.GitHubRepositoryInfo@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
@SC-AFI release draft was created [test.first.123456@8.1.1.2](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
@SC-AFI release draft was created [test.first.123456@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
@SC-AFI ** FAIL **: some errors occurred during the release draft being created [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.2](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
@SC-AFI Success: the release draft was created [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
@SC-AFI Failure: some **ERRORS** occurred during the release draft being created [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.2](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
@SC-AFI Success: the release draft was created [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
@SC-AFI Failure: some **ERRORS** occurred during the release draft was being created [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.2](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
@SC-AFI Success: the release draft was created [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
@SC-AFI Failure: some **ERRORS** occurred during the release draft was being created [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.2](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
@SC-AFI Success: the release draft was created [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
@SC-AFI Failure: some **ERRORS** occurred during the release draft was being created for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.2](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
@SC-AFI Success: the release draft was created for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
**Oops!**@SC-AFI, some **errors** occurred when creating the release draft for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.2](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/tag/8.1.1.2)

**Comment by SC-AFI** [comment]
**Success!**
@SC-AFI, the release draft was created for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/tag/8.1.1.3)

**Comment by SC-AFI** [comment]
**Success!**
@SC-AFI, the release draft was created for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/tag/5587006)

**Comment by SC-AFI** [comment]
**Success!**
@SC-AFI, the release draft was created for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/tag/22729557)

**Comment by SC-AFI** [comment]
**Success!**
@SC-AFI, the release draft was created for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/tag/5587161)

**Comment by SC-AFI** [comment]
**Oops!**@SC-AFI, some **errors** occurred when creating the release draft for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.2](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
**Success!**
@SC-AFI, the release draft was created for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
**Success!**
@SC-AFI, the release draft was created for [ReleaseDaemonTestOrganization/test.first.123456@https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases/tag/untagged-5f93420ca495146f9cf9](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases)

**Comment by SC-AFI** [comment]
**Success!**
@SC-AFI, the release draft was created for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases/tag/untagged-445b18cb94504fd3a929)

**Comment by SC-AFI** [comment]
**Oops!**
@SC-AFI, some **errors** occurred when creating the release draft for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.2](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases/tag/untagged-45bbc963f2e17db9d6aa)

**Comment by SC-AFI** [comment]
**Success!**
@SC-AFI, the release draft was created for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases/tag/untagged-c571bfc78339c58cd5d4)

**Comment by AndreyFilchenkov** [comment]
**Success!**
@SC-AFI, the release draft was created for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.1](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases/tag/untagged-fac1c482ddc868287101)

**Comment by AndreyFilchenkov** [comment]
**Oops!**
@SC-AFI, some **errors** occurred when creating the release draft for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.2](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases/tag/untagged-e6b2301107014024affe)

**Comment by AndreyFilchenkov** [comment]
**Success!**
@SC-AFI, the release draft was created for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases/tag/untagged-c3b842601a65f80d1fb7)

**Comment by AndreyFilchenkov** [comment]
Test

**Comment by AndreyFilchenkov** [comment]
test2

**Comment by AndreyFilchenkov** [comment]
@SC-AFI test3

**Comment by AndreyFilchenkov** [comment]
test4

**Comment by AndreyFilchenkov** [comment]
test5

**Comment by AndreyFilchenkov** [comment]
test6

**Comment by AndreyFilchenkov** [comment]
**Success!**
@SC-AFI, the release draft was created for [ReleaseDaemonTestOrganization/test.first.123456@8.1.1.3](https://github.com/ReleaseDaemonTestOrganization/test.first.123456/releases/tag/untagged-0f7a4557a0ea2c91a8b9)
